### ISSUE TITLE
error installing plugin

### ISSUE THREAD

**Issue by koren85** [southbridgeio/redmine_synchrony#5]
Hello.
An error occurs during the installation of the plug-in on the Redmine version 3.4 implementation of docker.
Error log below:

> redmine_1  | Installing plugins...
> redmine_1  | Installing gems required by plugins...
> redmine_1  | Migrating plugins. Please be patient, this could take a while...
> redmine_1  | rake aborted!
> redmine_1  | can't modify frozen Array
> redmine_1  | /home/redmine/redmine/plugins/redmine_synchrony/init.rb:3:in `<top (required)>'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
> redmine_1  | /home/redmine/redmine/lib/redmine/plugin.rb:155:in `block in load'
> redmine_1  | /home/redmine/redmine/lib/redmine/plugin.rb:146:in `each'
> redmine_1  | /home/redmine/redmine/lib/redmine/plugin.rb:146:in `load'
> redmine_1  | /home/redmine/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `block in load'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/engine.rb:652:in `block in load_config_initializer'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:166:in `instrument'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/engine.rb:651:in `load_config_initializer'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/engine.rb:615:in `each'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/engine.rb:615:in `block in <class:Engine>'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
> redmine_1  | /home/redmine/redmine/config/environment.rb:14:in `<top (required)>'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11/lib/rails/application.rb:457:in `block in run_tasks_blocks'
> redmine_1  | /home/redmine/redmine/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
> redmine_1  | Tasks: TOP => redmine:plugins:migrate => environment

**Comment by mboremski** [comment]
same issue here on redmine 4.0.4
